module.exports = {
  globals: {
    'ts-jest': {
      compiler: 'ttypescript',
    },
  },
  // automock: false,
  bail: 1,
  // browser: false,
  // cacheDirectory: "/private/var/folders/cn/2wdthgmj0s1glnwkszgqdjww0000gn/T/jest_dx",
  clearMocks: true,
  collectCoverage: true,
  collectCoverageFrom: ['./src/app/**/*.(ts|js)'],
  coverageDirectory: './__tests__/coverage',
  // coveragePathIgnorePatterns: ["/node_modules/"],
  coverageReporters: ['json', 'lcov'],
  // coverageThreshold: undefined,
  // dependencyExtractor: undefined,
  // errorOnDeprecated: false,
  // forceCoverageMatch: [],
  // globalSetup: undefined,
  // globalTeardown: undefined,
  // globals: {},
  // maxWorkers: "50%",
  // moduleDirectories: ['node_modules', 'src'],
  moduleFileExtensions: ['js', 'json', 'ts', 'node'],
  moduleNameMapper: {
    'src/(.*)': '<rootDir>/src/$1',
    'app/(.*)': '<rootDir>/src/app/$1',
    'controllers/(.*)': '<rootDir>/src/app/controllers/$1',
    'models/(.*)': '<rootDir>/src/app/models/$1',
    'repositories/(.*)': '<rootDir>/src/app/repositories/$1',
    'services/(.*)': '<rootDir>/src/app/services/$1',
  },
  // modulePathIgnorePatterns: [],
  // notify: false,
  // notifyMode: "failure-change",
  preset: 'ts-jest',
  // projects: undefined,
  // reporters: undefined,
  // resetMocks: false,
  // resetModules: false,
  // resolver: undefined,
  // restoreMocks: false,
  // rootDir: undefined,
  // roots: ['<rootDir>'],
  // runner: "jest-runner",
  // setupFiles: [],
  setupFilesAfterEnv: ['jest-extended'],
  // snapshotSerializers: [],
  testEnvironment: 'node',
  // testEnvironmentOptions: {},
  // testLocationInResults: false,
  testMatch: ['**/__tests__/**/*.test.ts'],
  // testPathIgnorePatterns: ["/node_modules/"],
  // testRegex: [],
  // testResultsProcessor: undefined,
  // testRunner: "jasmine2",
  // testURL: "http://localhost",
  testTimeout: 90000,
  // timers: "real",
  transform: {
    '^.+\\.(ts|js)$': 'ts-jest',
  },
  // transformIgnorePatterns: ['/node_modules/', './src/app/'],
  // unmockedModulePathPatterns: undefined,
  // verbose: undefined,
  // watchPathIgnorePatterns: [],
  // watchman: true,
};
